apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    prometheus: spin-prometheus
    component: spinnaker
    serviceapp: spinnaker
  name: spin-monitor
  namespace: monitoring
spec:
  endpoints:
    #  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
  - interval: 15s
    port: monitor
    path: /prometheus_metrics
  namespaceSelector:
    matchNames:
    - spinnaker
  selector:
    matchLabels:
      app: spin
  jobLabel: spin-monitor 
