apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: spin-prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: spin-prometheus
subjects:
- kind: ServiceAccount
  name: spin-prometheus
  namespace: monitoring

